move commands to scripts

diff --git a/evergreen/configs/ssdlc_util.yml b/evergreen/configs/ssdlc_util.yml
--- a/evergreen/configs/ssdlc_util.yml
+++ b/evergreen/configs/ssdlc_util.yml
@@ -15,55 +15,15 @@ variables:
 
 functions:
   "generate compliance report":
-    - command: shell.exec
+    - command: subprocess.exec
       type: test
       params:
-        shell: bash
-        working_dir: ${working_dir}
+        <<: *rust_subprocess_default_params
         include_expansions_in_env:
           - release_version
           - template_filepath
-        script: |
-          echo "Author = ${author}"
-          echo "Author email = ${author_email}"
-          echo "Version = ${release_version}"
-
-          SBOM_URL="https://translators-connectors-releases.s3.amazonaws.com/eap/${working_dir}/${working_dir}-${release_version}.sbom.json"
-          SARIF_URL="https://translators-connectors-releases.s3.amazonaws.com/eap/${working_dir}/${working_dir}-${release_version}.sast.sarif"
-
-          echo "Sbom url = $SBOM_URL"
-          echo "Sarif Url = $SARIF_URL"
-
-          echo "----- Generating ${COMPLIANCE_REPORT_NAME} -----"
-
-          # Copy template
-          echo "Copying template file from ${template_filepath} to ${COMPLIANCE_REPORT_NAME}"
-          cp ${template_filepath} ${COMPLIANCE_REPORT_NAME}
-
-          # Update the version
-          echo "Update the version"
-          echo "sed -i.bu "s,%VERSION%,${version},g" ${COMPLIANCE_REPORT_NAME}"
-          sed -i.bu "s,%VERSION%,${version},g" ${COMPLIANCE_REPORT_NAME}
-
-          # Update the SBOM link
-          echo "Update the SBOM link"
-          echo "sed -i.bu "s,%SBOM_URL%,$SBOM_URL,g"${COMPLIANCE_REPORT_NAME}"
-          sed -i.bu "s,%SBOM_URL%,$SBOM_URL,g" ${COMPLIANCE_REPORT_NAME}
-
-          # Update the SARIF link
-          echo "Update the SARIF link"
-          echo "sed -i.bu "s,%SARIF_URL%,$SARIF_URL,g" ${COMPLIANCE_REPORT_NAME}"
-          sed -i.bu "s,%SARIF_URL%,$SARIF_URL,g" ${COMPLIANCE_REPORT_NAME}
-
-          # Update the author information
-          echo "Update the author name"
-          echo "sed -i.bu "s,%AUTHOR%,${author},g" ${COMPLIANCE_REPORT_NAME}"
-          sed -i.bu "s,%AUTHOR%,${author},g" ${COMPLIANCE_REPORT_NAME}
-
-          echo "update the author email"
-          echo "sed -i.bu "s,%AUTHOR_EMAIL%,${author_email},g" ${COMPLIANCE_REPORT_NAME}"
-          sed -i.bu "s,%AUTHOR_EMAIL%,${author_email},g" ${COMPLIANCE_REPORT_NAME}
-          echo "---------------------------"
+        args:
+          - ${script_dir}/generate_compliance_report.sh
     - command: s3.put
       params:
         # SQL-2918: we should use aws assume role instead once all the projects are set up this way.
@@ -76,65 +36,68 @@ functions:
         permissions: public-read
     
   "scan SBOM":
-    - command: shell.exec
+    # - command: shell.exec
+    - command: subprocess.exec
       type: test
       params:
-        shell: bash
-        working_dir: ${working_dir}
-        script: |
-          ${prepare_shell}
+        <<: *rust_subprocess_default_params
+        args:
+          - ${script_dir}/scan_sbom.sh
+        # script: |
+        #   echo ">>>> Scan SBOM for vulnerabilities..."
+        #   if [[ "$ALLOW_VULNS" != "" ]]; then
+        #     echo "Vulnerability ids to ignore : $ALLOW_VULNS"
 
-          echo ">>>> Scan SBOM for vulnerabilities..."
-          if [[ "$ALLOW_VULNS" != "" ]]; then
-            echo "Vulnerability ids to ignore : $ALLOW_VULNS"
+        #     echo "-- Generate .grype.yaml specifying vulnerabilities to ignore --"
+        #     GRYPE_CONF_FILE=".grype.yaml"
+        #     touch $GRYPE_CONF_FILE
+        #     echo "ignore:" > $GRYPE_CONF_FILE
 
-            echo "-- Generate .grype.yaml specifying vulnerabilities to ignore --"
-            GRYPE_CONF_FILE=".grype.yaml"
-            touch $GRYPE_CONF_FILE
-            echo "ignore:" > $GRYPE_CONF_FILE
+        #     IFS=','; for VULN_ID in $ALLOW_VULNS; do
+        #       echo "Ignoring vulnerability with id $VULN_ID"
+        #       echo "    - vulnerability: $VULN_ID" >> $GRYPE_CONF_FILE
+        #     done
+        #     echo "------------------------------------"
+        #   fi
 
-            IFS=','; for VULN_ID in $ALLOW_VULNS; do
-              echo "Ignoring vulnerability with id $VULN_ID"
-              echo "    - vulnerability: $VULN_ID" >> $GRYPE_CONF_FILE
-            done
-            echo "------------------------------------"
-          fi
-
-          echo "-- Scanning dependency for vulnerabilities --"
-          ./$SBOM_DIR/grype sbom:$SBOM_LICENSES --fail-on low
-          echo "---------------------------------------------"
-          echo "<<<< Done scanning SBOM"
+        #   echo "-- Scanning dependency for vulnerabilities --"
+        #   ./$SBOM_DIR/grype sbom:$SBOM_LICENSES --fail-on low
+        #   echo "---------------------------------------------"
+        #   echo "<<<< Done scanning SBOM"
 
   "generate static code analysis":
-    - command: shell.exec
+    # - command: shell.exec
+    - command: subprocess.exec
       type: test
       params:
-        shell: bash
-        working_dir: ${working_dir}
-        script: |
-          ${prepare_shell}
-          export SEMGREP_APP_TOKEN=${semgrep_app_token}
-          echo "Running static code analysis with Semgrep..."
+        <<: *rust_subprocess_default_params
+        args:
+          - ${script_dir}/generate_static_code_analysis.sh
+        # shell: bash
+        # working_dir: ${working_dir}
+        # script: |
+        #   export SEMGREP_APP_TOKEN=${semgrep_app_token}
+        #   echo "Running static code analysis with Semgrep..."
 
-          # Setup or use the existing virtualenv for semgrep
-          if [[ -f "venv/bin/activate" ]]; then
-              echo 'using existing virtualenv'
-              . venv/bin/activate
-          else
-              echo 'Creating new virtualenv'
-              python3 -m virtualenv venv
-              echo 'Activating new virtualenv'
-              . venv/bin/activate
-          fi
-          python3 -m pip install semgrep
-          # Confirm semgrep version
-          semgrep --version
-          set +e
-          semgrep --config p/rust --sarif --exclude "integration_test" --verbose --error --severity=ERROR --sarif-output=${STATIC_CODE_ANALYSIS_NAME} > ${STATIC_CODE_ANALYSIS_NAME}.cmd.verbose.out 2>&1
-          SCAN_RESULT=$?
-          set -e
-          # Exit with a failure if the scan found an issue
-          exit $SCAN_RESULT
+        #   # Setup or use the existing virtualenv for semgrep
+        #   if [[ -f "venv/bin/activate" ]]; then
+        #       echo 'using existing virtualenv'
+        #       . venv/bin/activate
+        #   else
+        #       echo 'Creating new virtualenv'
+        #       python3 -m virtualenv venv
+        #       echo 'Activating new virtualenv'
+        #       . venv/bin/activate
+        #   fi
+        #   python3 -m pip install semgrep
+        #   # Confirm semgrep version
+        #   semgrep --version
+        #   set +e
+        #   semgrep --config p/rust --sarif --exclude "integration_test" --verbose --error --severity=ERROR --sarif-output=${STATIC_CODE_ANALYSIS_NAME} > ${STATIC_CODE_ANALYSIS_NAME}.cmd.verbose.out 2>&1
+        #   SCAN_RESULT=$?
+        #   set -e
+        #   # Exit with a failure if the scan found an issue
+        #   exit $SCAN_RESULT
     - command: s3.put
       params:
         # SQL-2918: we should use aws assume role instead once all the projects are set up this way.
